hotosm/drone-tm

- src/backend/app/config.py
- src/backend/app/db/db_models.py
- src/backend/app/main.py
- src/backend/app/users/user_crud.py
- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
- src/backend/pdm.lock
- src/backend/pyproject.toml
This pull request includes a user authentication system, enabling users to securely register, log in, and log out.
> Implement User Authentication System

- src/backend/app/projects/project_crud.py
N/A
This PR implements the bounding box (bbox) information on the project list. It introduces existing endpoints and functions to handle project retrieval in the application. The key changes include:
1. ** Endpoints:**
- `GET /projects`: Returns a list of projects with optional `skip` and `limit` query parameters for pagination.
2. **Supporting Functions:**
- `get_projects`: Fetches all projects from the database with pagination support.
- `convert_to_app_projects`: Converts database project models to Pydantic models, including bbox info.
No alternative approaches were considered for this implementation as the solution aligns with the existing architecture and requirements.
1. **Setup**: Ensure your database is populated with some projects.
2. **Test the List Endpoint**: 
- Make a GET …
> feat: Implement bbox info on project list

- src/frontend/src/components/UserProfile/FormContents/BasicDetails/index.tsx
- src/frontend/src/components/UserProfile/FormContents/OrganizationDetails/index.tsx
- src/frontend/src/components/UserProfile/FormContents/Password/index.tsx
- src/frontend/src/components/UserProfile/FormContents/index.tsx
- src/frontend/src/components/common/FormUI/Select/index.tsx
- src/frontend/src/constants/index.ts
- src/frontend/src/store/slices/common.ts
- src/frontend/src/views/UserProfile/UserProfileTabs/index.tsx
- src/frontend/src/views/UserProfile/index.tsx
- Add Tabs component for userProfile section.
- Add global state for tabs in userProfile section.
- Add UserProfile form section.
> User Profile Form Initial Slicing

- .github/workflows/build_and_deploy_DTM_backend.yml
- .github/workflows/build_and_deploy_DTM_frontend.yml
- .github/workflows/migrations.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test_frontend.yml
- feat: add ci for database migrations
- fix: clone stage
- fix: clone with ref instead of ref_name
> Fix Clone stage in CI

- .github/workflows/build_and_deploy.yml
- Added timeout for workflow stage so that workflow won't keep running for unusual period of time.
> ci: added build timeout for infinitely hanging build steps

- src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
- src/frontend/src/components/CreateProject/FormContents/DefineAOI/index.tsx
- src/frontend/src/components/CreateProject/FormContents/GenerateTask/MapSection/index.tsx
- src/frontend/src/components/CreateProject/FormContents/GenerateTask/index.tsx
- src/frontend/src/store/slices/createproject.ts
Fix and enhance project creation process
- Increase drawn area limit to 100km2
- Update placeholder text in generate task section
- Make no-fly zones optional in task split POST request
- Clear form state after creating a project
> create project issues

- src/backend/app/projects/project_crud.py
###Related Issues
Fix #93 : Handle no_fly_zones conversion to string or None
> fix: Handle None values for  in project metadata

- src/frontend/src/components/Dashboard/DashboardSidebar/index.tsx
- This PR enables the user to view their details on the profile section
Below is the screenshot of the details displayed on the profile section
> feat: Show user details on profile section

- src/frontend/src/components/common/MapLibreComponents/types/index.ts
This PR makes image as a optional prop on vector layer component so it won't make an issue although the image is not found on vector layer component
> fix: build issue

- src/backend/app/email_templates/mapping_requests.html
- src/backend/app/migrations/versions/06668eb5d14a_.py
- src/backend/app/migrations/versions/1ebfe5e4cf1c_add_overlap_in_projects_table.py
- src/backend/app/migrations/versions/3293e9c98b2a_.py
- src/backend/app/migrations/versions/4b1534031978_add_gcp_table.py
- src/backend/app/migrations/versions/62a16e505bc3_.py
- src/backend/app/migrations/versions/87b6f9d734e8_.py
- src/backend/app/migrations/versions/88ae62ec8876_.py
- src/backend/app/migrations/versions/9d01411fd221_.py
- src/backend/app/migrations/versions/ac09917990dc_.py
- src/backend/app/migrations/versions/acee47666167_refine_field_name.py
- src/backend/app/migrations/versions/bf26afac872d_.py
- src/backend/app/migrations/versions/d2b9d45d3ede_initial_migration.py
- src/backend/app/migrations/versions/fa5c74996273_.py
hot-fix: Email format changes when drone operator requests mapping
> fix(email-templates): changes email format

- .env.example
- docker-compose.vm.yml
- docker-compose.yml
> fix: minio console accessible from internet

- src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
- src/frontend/src/components/CreateProject/FormContents/KeyParameters/index.tsx
- src/frontend/src/components/Dashboard/DashboardCard/index.tsx
- src/frontend/src/components/Dashboard/RequestLogs/index.tsx
- src/frontend/src/components/Dashboard/TaskLogs/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/constants/dashboard.ts
- src/frontend/src/views/Dashboard/index.tsx
> Feat: refactor dashboard UI and update project creation payload keys

- src/frontend/src/components/CreateProject/CreateProjectHeader/index.tsx
- src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
- src/frontend/src/components/CreateProject/FormContents/DefineAOI/MapSection/index.tsx
- src/frontend/src/components/CreateProject/FormContents/DefineAOI/MapTools/index.tsx
- src/frontend/src/components/CreateProject/FormContents/DefineAOI/index.tsx
- src/frontend/src/components/CreateProject/FormContents/GenerateTask/MapSection/index.tsx
- src/frontend/src/components/CreateProject/FormContents/KeyParameters/index.tsx
- src/frontend/src/components/CreateProject/StepSwitcher/index.tsx
- src/frontend/src/components/CreateProject/index.tsx
- src/frontend/src/components/Dashboard/DashboardCard/index.tsx
- src/frontend/src/components/Dashboard/DashboardSidebar/index.tsx
- src/frontend/src/components/Dashboard/RequestLogs/index.tsx
- src/frontend/src/components/Dashboard/TaskLogs/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/DescriptionComponent/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/LandingPage/Home/index.tsx
- src/frontend/src/components/Projects/MapSection/index.tsx
- src/frontend/src/components/Projects/ProjectCard/MapSection/index.tsx
- src/frontend/src/components/Projects/ProjectCard/index.tsx
- src/frontend/src/services/tasks.ts
- src/frontend/src/views/Dashboard/index.tsx
- src/frontend/src/views/IndividualProject/index.tsx
- src/frontend/src/views/Projects/index.tsx
- src/frontend/src/views/TaskDescription/index.tsx
- src/frontend/src/views/UserProfile/index.tsx
screenshot of error-boundary preventing the whole page crash while map section has an issue:
> feat: Implement error boundary and update minor changes

- src/backend/app/projects/project_crud.py
- src/backend/app/projects/project_schemas.py
- **Added Task Status:** Implemented tracking for the current status of tasks.
- **User ID:** Integrated user identification within project  task details.
- **Name:** Included user  name in  each task.
- **Task Area:** Assigned specific areas to tasks within the project.
> Feat: update project details endpoint

- src/backend/app/projects/project_crud.py
- src/backend/app/projects/project_routes.py
- src/backend/app/tasks/task_crud.py
- src/backend/app/tasks/task_routes.py
This pull request updates the handling of task events and statistics in the API.
- **Task Events API**: Modified the SQL query in `/api/tasks/event/{project_id}/{task_id}` to perform an insert operation instead of an update. This ensures that every new event is recorded as a separate entry with its state.
- **Task Statistics API**: Updated the SQL query in `/api/tasks/statistics/` to reflect the new behavior of task events. 
- **Task API**: Adjusted the SQL query in `/api/tasks/` to align with the changes made to task events and statistics.
> Fix:  updates the handling of task events and statistics in the API.

- src/frontend/package.json
- src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
- src/frontend/src/components/Dashboard/RequestLogs/index.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/index.tsx
- src/frontend/src/components/LandingPage/Home/index.tsx
- src/frontend/src/components/Projects/ProjectCard/index.tsx
- src/frontend/src/components/common/MapLibreComponents/Layers/VectorLayer.ts
- src/frontend/src/components/common/MapLibreComponents/types/index.ts
- src/frontend/src/components/common/Navbar/index.tsx
- src/frontend/src/constants/index.ts
- src/frontend/src/modules/user-auth-module/src/components/Authentication/Login/index.tsx
- src/frontend/src/routes/types.ts
- src/frontend/src/views/IndividualProject/index.tsx
- In the previous version response points were on the list now the points are on Geojson so in frontend, the response is directly rendered without any data refinement for points and created lineString from the same geojson by combining the points with the help of `coordAll` function available on `'@turf/meta'`.
> Feat: Implement updated flightplan generation waypoint  response

- src/backend/app/projects/project_crud.py
- src/backend/app/projects/project_schemas.py
- Added `no_fly_zones_geojson` property to generate geojson from `no_fly_zones`.
- Updated `no_fly_zones` field to be optional and excluded from serialization.
> Feat: add no-fly-zones project details

- src/frontend/src/components/CreateProject/FormContents/KeyParameters/index.tsx
> feat: Update GSD unit

- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/common/MapLibreComponents/AsyncPopup/index.tsx
- src/frontend/src/components/common/MapLibreComponents/types/index.ts
> Fix: Showing popup on all layer

- src/frontend/src/constants/landingPage.tsx
> Fix: Typo error

- src/backend/app/projects/project_logic.py
- src/backend/app/tasks/splitter.py
- src/backend/app/users/auth.py
- src/backend/app/users/user_deps.py
- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
This PR introduces an enhancement to the `TaskSplitter` class by adding functionality to merge small polygons that are adjacent to each other during the polygon splitting process. The key changes include:
- **Small Polygon Identification**: Small polygons are identified based on an area threshold calculated using the square grid size. Polygons can only be merged if their area is equal to or less than 25% of the grid square size.
- **Adjacent Polygon Merging**: If a small polygon touches a larger or small polygon, it is merged with the nearest small polygon. 
- **Preservation of Single Polygons**: In cases where no adjacent polygon is found, the small polygon is added as-is.
- Updated `splitBySquare` method in `TaskSplitter` class.
- Added logic for merging small polygons with adjacent …
> feat: added logic for merging small polygons with adjacent small polygons.

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
> fix: download fligh plan

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
- Make a request using `fetch` and read a `Blob` out of the response using `blob()`, put it into an object URL using `URL.createObjectURL` , add anchor tag, set download attribute, and set blob URL as a href and click manually and remove anchor tag from the DOM.
> feat: download fligh plan

- src/backend/app/waypoints/waypoint_routes.py
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
Waypoints geojson download feature is added here like this
> Download Waypoints Geojson File

- src/backend/app/config.py
- src/backend/app/email_templates/password/password_reset.html
- src/backend/app/projects/project_routes.py
- src/backend/app/tasks/task_routes.py
- src/backend/app/users/user_deps.py
- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
- src/backend/app/utils.py
This PR adds a password reset feature to the application and introduces the following changes:
- Added JWT-based token generation for password reset.
- Integrated `aiosmtplib` for sending reset password emails.
- Configured SMTP settings with TLS, SSL, and custom sender details.
- Created API endpoints for forgot password and password reset workflows.
- Utilized user-defined schemas and JWT token handling for secure password resets.
> Feat: implement forgot password functionality with email reset link

- src/frontend/src/components/DroneOperatorTask/MapSection/GetCoordinatesOnClick.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/Projects/MapSection/index.tsx
- src/frontend/src/components/common/BaseLayerSwitcher/index.tsx
- src/frontend/src/components/common/MapLibreComponents/AsyncPopup/index.tsx
- src/frontend/src/components/common/MapLibreComponents/types/index.ts
- src/frontend/src/views/IndividualProject/index.tsx
screenshot of the project description page on mobile view:
> Feat: Implement task unlock feature and make project description responsive

- src/frontend/src/App.tsx
- src/frontend/src/components/UserProfile/FormContents/Password/index.tsx
- src/frontend/src/components/common/Navbar/index.tsx
- src/frontend/src/components/common/ScrollToTop/index.tsx
- src/frontend/src/views/TaskDescription/index.tsx
- src/frontend/src/views/UserProfile/index.tsx
screenshot of the project description page showing scroll to top button on mobile view:
> Feat: add scroll to top button and make user profile page responsive

- src/backend/app/projects/project_routes.py
- src/backend/app/utils.py
- Added a new feature to support KML export in the `download boundaries` API.
- Implemented the `geojson_to_kml` function, which converts GeoJSON data to KML format, including handling of `Point`, `LineString`, and `Polygon` geometries.
- Ensured the API dynamically generates file names for both `geojson` and `kml` exports based on the task and project data.
- Adjusted the response headers to correctly set content types and file names for KML downloads.
> Feat: added KML download format in download boundaries API

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
- src/frontend/src/components/Projects/ProjectsHeader/index.tsx
> Feat: Download task area on kml/geojson format and minor UI fixes

- src/frontend/src/components/CreateProject/FormContents/GenerateTask/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/ImageBox/index.tsx
- src/frontend/src/services/tasks.ts
> Feat: Trigger image processing starter api

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/ImageBox/index.tsx
- src/frontend/src/utils/callApiSimultaneously.ts
Created the recursive function that retries the failed api calls after 1 sec for given number of times
```
const retryFc = async (url: string, singleData: any, n: number) => {
try {
return await axios.put(url, singleData);
} catch (err) {
if (n === 1) throw err;
delay(1000); // 1 sec delay
return await retryFc(url, singleData, n - 1);
}
}
```
> Feat: Retry on api failure on image upload and image processing trigger.

- src/backend/app/projects/project_routes.py
- src/backend/app/projects/project_schemas.py
- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
- Added a new route `/api/users/` to retrieve all users asynchronously.
- Implemented user restrictions on project deletion, allowing only the project creator or authorized users to delete the project.
> Feat: user management (retrieve all users)

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
> fix: Remove BLOb

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
> Feat: Show task lock date

- src/backend/app/users/user_routes.py
hot-fix(user-profile): check old & new password before verify the password
> hot-fix(user-profile): check old & new password before verify the password

- src/backend/app/projects/project_routes.py
- src/backend/app/projects/project_schemas.py
This PR adds search functionality to the project read endpoint. Users can now search by project name.
> feat: added search features in projects lists.

- src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
- src/frontend/src/views/IndividualProject/index.tsx
Show the image count and download orthophoto button on project listing table:
Screenshot:
> Feat: Download orthophoto form project description page

- src/frontend/src/components/Dashboard/DashboardSidebar/index.tsx
- src/frontend/src/components/Dashboard/TaskLogs/TaskLogsTable.tsx
- src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/Contributions/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/Legend.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/index.tsx
- src/frontend/src/components/Projects/MapSection/VectorLayerWithCluster.tsx
- src/frontend/src/components/Projects/MapSection/index.tsx
- src/frontend/src/components/Projects/ProjectCard/index.tsx
- src/frontend/src/components/RadixComponents/Table.tsx
- src/frontend/src/components/common/Chip/StatusChip/index.tsx
- src/frontend/src/views/IndividualProject/index.tsx
- src/frontend/src/views/Projects/index.tsx
- src/frontend/src/views/UpdateUserProfile/index.tsx
> Feat: Show project status and task status on map and project cards

- src/frontend/src/api/projects.ts
- src/frontend/src/components/Dashboard/DashboardSidebar/index.tsx
- src/frontend/src/components/LandingPage/SignInOverlay/index.tsx
- src/frontend/src/components/Projects/MapSection/index.tsx
- src/frontend/src/components/Projects/ProjectsHeader/index.tsx
- src/frontend/src/components/common/UserProfile/index.tsx
- src/frontend/src/modules/user-auth-module/src/components/Authentication/Login/index.tsx
- src/frontend/src/services/createproject.ts
- src/frontend/src/views/CompleteUserProfile/index.tsx
- src/frontend/src/views/Dashboard/index.tsx
- src/frontend/src/views/Projects/index.tsx
- src/frontend/src/views/UpdateUserProfile/index.tsx
> Fix: Implement roles received as array and  show all projects on map

- src/backend/app/migrations/versions/4ea77c60b715_.py
- src/backend/app/models/enums.py
- src/backend/app/projects/image_processing.py
- src/backend/app/projects/project_routes.py
- src/backend/app/tasks/task_logic.py
- src/backend/app/tasks/task_routes.py
- src/backend/app/tasks/task_schemas.py
- Added a new state `IMAGE_PROCESSING_FAILED` to handle scenarios where image processing fails.
- Fixed the output path cleanup when image processing fails.
- Updated task details and stats endpoints to reflect the new state.
> feat: added new state for image processing failed

- src/backend/app/projects/image_processing.py
- src/backend/app/projects/project_routes.py
The changes made to the `image_processing.py` and `project_routes.py` files involve updating how database connections are handled during image processing tasks. 
1. Database connection pooling:
- Previously, the code used the `app.state.db` for managing database connections.
- Now, I've switched to using direct database connections, ensuring that a connection pool is used (`database.get_db_connection_pool()`), which should reduce issues with processing tasks.
These changes have been tested on the following project to ensure that image processing works correctly & update status of task:  [Link](https://dev.dronetm.org/projects/2f9bfad0-62b5-4521-a5d5-c469baca3951)
> [hotfix]: slove the status not updated after image processing

- src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/Contributions/index.tsx
- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/TableSection/index.tsx
- src/frontend/src/components/IndividualProject/Tasks/index.tsx
- src/frontend/src/components/Projects/MapSection/index.tsx
- src/frontend/src/components/common/DataTable/index.tsx
- src/frontend/src/components/common/MapLibreComponents/AsyncPopup/index.tsx
- src/frontend/src/components/common/MapLibreComponents/types/index.ts
- src/frontend/src/components/common/UserProfile/index.tsx
- src/frontend/src/store/slices/project.ts
- src/frontend/src/views/IndividualProject/index.tsx
- src/frontend/src/views/Projects/index.tsx
This PR introduces a feature that simulates a popup when a task is clicked, both from the task on the map and the task on the table.
> Feat: fire popup manually

- src/frontend/src/components/DroneOperatorTask/ModalContent/TaskOrthophotoPreview.tsx
This approach minimizes unnecessary data requests, improving map performance and reducing bandwidth usage.
> feat: Implemented viewport-based tile loading for orthophotos.

- src/backend/app/tasks/task_splitter.py
Fixes #320
- Set tasks to a square shape for a consistent look, fixing an issue where tasks appeared rectangular in some regions (far from equator).
> fix: add task dimension controls and default to square shape

- .env.example
- src/frontend/src/components/DroneOperatorTask/ModalContent/TaskOrthophotoPreview.tsx
- src/frontend/src/components/Projects/MapSection/VectorLayerWithCluster.tsx
- src/frontend/vite.config.ts
> Feat: update COG url

- src/backend/app/waypoints/waypoint_routes.py
> fix: update take-off point from 200m to 350m

- src/frontend/src/components/IndividualProject/MapSection/index.tsx
- src/frontend/src/components/LandingPage/Home/index.tsx
- src/frontend/src/components/RegulatorsApprovalPage/Description/ApprovalSection.tsx
- src/frontend/src/components/RegulatorsApprovalPage/Description/DescriptionSection.tsx
- src/frontend/src/components/RegulatorsApprovalPage/DescriptionSection.tsx
- src/frontend/src/components/RegulatorsApprovalPage/index.tsx
- src/frontend/src/components/common/Navbar/index.tsx
- src/frontend/src/routes/appRoutes.ts
- src/frontend/src/services/createproject.ts
- src/frontend/src/views/IndividualProject/index.tsx
- src/frontend/src/views/RegulatorsApprovalPage/index.tsx
> Feat: Enhancements to Regulators Approval Flow on project creation

- src/backend/app/email_templates/mapping/task_marked_unflyable.html
- src/backend/app/tasks/task_logic.py
- src/backend/app/users/user_schemas.py
- src/backend/pdm.lock
- src/backend/pyproject.toml
Example: Fixes #53  #329
Upgraded `drone-flightplan` to version `>=0.3.2` and added email notifications for project author, marked as  unflyable task state.
> feat: update drone-flightplan to v0.3.2 and notify project creator on unflyable task state

- src/frontend/package.json
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/MapBox/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsBox/index.tsx
- src/frontend/src/components/common/MapLibreComponents/AsyncPopup/index.tsx
- src/frontend/src/constants/modalContents.tsx
- src/frontend/src/store/actions/droneOperatorTask.ts
- src/frontend/src/store/slices/droneOperartorTask.ts
- src/frontend/src/utils/exifDataToGeoJson.ts
- src/frontend/src/utils/getExifData.ts
- src/frontend/src/utils/sortArrayUsingDate.ts
- Add modal to plot image coordinates
- Add function to extract exif data
- Add fucntion to convert exif data to geoJson data
- Add functions to upload images
- Add function to sort array of objects using dateTime property
- Update asyncPopup component to HOC and add forward ref
> Feat/drone operator image upload UI

- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
Update roles for an existing user when automatically creating a local regulator.
If an email already exists in the system, the regulator user will not be created. Instead, the existing user's roles will be updated.
> fix: update roles in existing user when auto local regulator creation

- src/backend/app/users/user_routes.py
- src/backend/app/users/user_schemas.py
Example: Fixes #123
A brief description of how this solves the issue.
> fix: reslove user roles access issues with regulator

- src/backend/app/tasks/task_logic.py
- src/backend/app/tasks/task_schemas.py
This PR addresses two  issues:  
1. The project creator was unable to lock tasks.  
2. A validation error occurred in the `TaskDetailsOut` schema, where the `gsd_cm_px` field expected a float but received a `None` value.
> fix: slove task locking and validation error in project creator

- src/backend/app/gcp/gcp_crud.py
- src/backend/app/gcp/gcp_routes.py
- src/backend/app/main.py
- src/backend/app/projects/image_processing.py
- src/backend/app/projects/project_routes.py
- src/backend/app/users/user_routes.py
This PR introduces an API endpoint to identify and retrieve the list of drone images that contain a specified GPS point (GCP). The functionality is essential for determining which images collected by drone operators contains a GCP Point collected by project creators.
I have  added a new endpoint to accept GPS coordinates, project id and task id as input. The api returns the list of images that contains the specific point.  `images.json` file provided by the OpenDroneMap (ODM) is used to gain the information of the individual images to calculate the bounding box of each images.
1. Images collected by the drone operators are uploaded by the drone operators themselves.
2. The processing of those images are done using OpenDroneMap (ODM).
3. GCP points collected are plotted in the orthophoto …
> Create a list of Images that contains a GCP Point

- src/backend/pyproject.toml
- src/backend/uv.lock
Upgrade the drone_flightplan version to 0.3.3rc1
> bump drone_flightplan version

- docs/about/faq.md
Fixes #401 
Added Frequently added questions for documentation update
> Update faq section to add basic frequently asked questions.md

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
> fix: update response for flight plan

- src/backend/app/models/enums.py
- src/backend/app/waypoints/waypoint_routes.py
- src/backend/pyproject.toml
- src/backend/uv.lock
- src/frontend/src/api/tasks.ts
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/constants/taskDescription.ts
- src/frontend/src/services/tasks.ts
- src/frontend/src/store/actions/droneOperatorTask.ts
- src/frontend/src/store/slices/droneOperartorTask.ts
This Pull request introduces a new feature that allow the user to access the wayline flight with the terrrain following.
> Implement Waylines flight mode in flights with terrain following enabled.

- src/backend/app/projects/image_processing.py
- src/backend/app/s3.py
- src/backend/app/tasks/task_routes.py
issues solve on task table update
- Update all image processing without gcp files
- issue solve in task table from dummy api.
> Update all image processing without gcp files

- src/backend/app/tasks/task_routes.py
A brief description of how this solves the issue.
> Solve  issuues on flight plan time & distance  in task table.

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/LoadingBox/index.tsx
> feat: Task description data refetch 

- src/frontend/src/views/IndividualProject/index.tsx
Add image URL as a prop to fetch images as per coordinates
> feat: add image url to gcp editor

- src/backend/app/waypoints/waypoint_routes.py
- src/frontend/src/api/tasks.ts
- src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/MapSection.tsx
- src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
- src/frontend/src/services/tasks.ts
- src/frontend/src/store/actions/droneOperatorTask.ts
- src/frontend/src/store/slices/droneOperartorTask.ts
- src/frontend/src/views/TaskDescription/index.tsx
> Feat/ implement flight plan rotation from backend response

- src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/MapBox/index.tsx
- src/frontend/src/components/RegulatorsApprovalPage/Description/DescriptionSection.tsx
- src/frontend/src/components/common/MapLibreComponents/Layers/VectorLayer.ts
- src/frontend/src/components/common/MapLibreComponents/NewAsyncPopup/index.tsx
- src/frontend/src/components/common/MapLibreComponents/types/index.ts
Below is the screenshot where green stroked points are selected for deletion :
> Feat: Implement multiple image deletion

- src/backend/app/projects/image_processing.py
Changes
========================
- Removed random uuid for the image name. task_id prefix is kept for each image. Random name resulted in the processing failed in the ODM.
- Removed duplicate code in the wehook implementation in the process_imagery
> Fix minor issues in the drone image processing 

- src/backend/app/users/user_schemas.py
Update user profile to add OAM API Token
> update user profile to add oam api token

- src/frontend/src/views/IndividualProject/index.tsx
> fix: orthophoto persist on project change

- src/backend/app/projects/project_routes.py
- src/backend/app/users/permissions.py
- src/backend/app/users/user_deps.py
Different custom permission classes have been created.
Some of them are :
`check_permissions`  dependency function is created that handles all the permissions classes passed into this function from routes and checks the relevant permissions.
An example of such endpoints looks like this:
```
@router.delete("/{project_id}", tags=["Projects"])
async def delete_project_by_id(
db: Annotated[Connection, Depends(database.get_db)],
project: Annotated[
project_schemas.DbProject,
Depends(
check_permissions(
IsSuperUser() | IsProjectCreator(),
get_obj=project_deps.get_project_by_id,
)
),
],
):
project_id = await project_schemas.DbProject.delete(db, project.id)
return {"message": f"Project successfully deleted {project_id}"}
```
In this endpoint, 2 permissions are checked, IsSuperUser and …
> Created custom permission classes and implementation in api endpoints

- src/frontend/src/components/RegulatorsApprovalPage/Description/DescriptionSection.tsx
Show `Upload to OAM` button only to the project's author.
> feat: Add condition to show `Upload to OAM` button 

- src/backend/app/arq/tasks.py
- src/backend/app/projects/image_processing.py
- src/backend/app/projects/oam.py
- src/backend/app/projects/project_logic.py
- src/backend/app/projects/project_routes.py
- src/backend/app/s3.py
Improve the handling of projects with only a single task by:
- Automatically copying the orthophoto to the project-level directory
- Copying the assets zip file to the project-level directory
- Marking the project processing status as completed
- Added logic to detect when a project has only one task
- Implemented file copying for orthophoto and assets to project-level storage
- Updated project processing status to SUCCESS when conditions are met
This change simplifies the workflow for single-task projects by:
- Eliminating redundant processing
- Ensuring project-level files are readily accessible
- Not necessary to process twice for the projects containing a single task within a project
Also, the processing of whole project has been moved from the fastapi background tasks to the arq …
> Handling Single-Task Projects Processing

- src/frontend/src/components/LandingPage/MobileAppDownload/index.tsx
Updated the apk download link on landing page
> Update apk url

- src/frontend/src/components/LandingPage/MobileAppDownload/index.tsx
Fix apk download issue, updated the apk download link (APK serving through S3 instead of Google Drive).
> Update mobile app apk download link
