src/backend/app/config.py
src/backend/app/users/user_crud.py
src/backend/app/users/user_deps.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

Updated authentication workflows:

Feat authentication

---

src/backend/app/projects/project_routes.py

This PR enhances the `delete_project_by_id` endpoint to ensure that when a project is deleted, all associated tasks are also deleted. This prevents orphaned tasks and maintains database integrity.
- Updated the `delete_project_by_id` function to query and delete tasks associated with the project before deleting the project itself.
- Added docstrings to the function for better documentation and clarity.
1. Create a project and associated tasks in the database.
2. Use the `/projects/{project_id}` DELETE endpoint to delete the project.
3. Verify that the project and all associated tasks are deleted from the database.

feat: Add deletion of associated tasks when deleting a project

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_schemas.py

This PR adds the following to the project detail API:
- Contributor information
- Task state
- Outline of each task
- Also remove short description
- Updated `@router.get("/{project_id}", tags=["Projects"], response_model=project_schemas.ProjectOut)` to include the new fields.
- Updated schemas and relevant logic to handle the new data.

feat: add contributor, task state, and outline to project detail API

---

src/backend/app/users/oauth_routes.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

This PR addresses two key improvements:
1. **Refresh Token Access**: Fixes the issue with refresh token access, ensuring that tokens are handled correctly for maintaining user sessions.
2. **Profile Update with PATCH**: Implements the ability to update user profiles using the PATCH method, allowing partial updates to user information.
- **Auth**: Updated the logic for managing and validating refresh tokens.
- **Profile**: Added support for updating user profiles with partial data using the PATCH method.
- Verify that refresh tokens are correctly issued and validated.
- Test updating user profiles with partial data to ensure that changes are applied correctly.
---
Feel free to adjust any details as needed!

feat(auth/profile): solve refresh token access and update profile with with PATCH method

---

.github/workflows/build_and_deploy.yml
contrib/pg-upgrade/Dockerfile
contrib/pg-upgrade/README.md
contrib/pg-upgrade/docker-compose.yml
contrib/pg-upgrade/upgrade-db.sh
docker-compose.vm.yml
docker-compose.yml

Fixes #72
- Upgrading Postgres 14 --> 16, including a migration for the live server.
- This was harder than I imagined!
- I made a separate docker-compose file to orchestrate the database upgrade.
- A script `contrib/pg-upgrade/upgrade-db.sh` can be used to automate the upgrade process.
- It checks if the upgrade has already taken place & is idempotent, so can be ran at every compose restart if required.
- See the comments in the compose file to see what each stage does.
- When redeploying to the AWS VM, it should upgrade automatically 🤞 
Let me know feedback / if anyone knows an easier way!
This is based on https://github.com/tianon/docker-postgres-upgrade

Upgrade Postgres v14 --> v16, plus migration for live server

---

src/backend/app/tasks/task_crud.py
src/backend/app/tasks/task_routes.py
src/backend/app/tasks/task_schemas.py

This PR adds a new endpoint to list all tasks for drone users. It includes role validation to ensure only users with the `DRONE_PILOT` role can access the endpoint. Additionally, the `get_tasks_by_user` function has been updated to calculate the task area and render task data using the `UserTasksStatsOut` Pydantic model.
- Added endpoint to list all tasks for drone users with role validation.
- Implemented task area calculation in the `get_tasks_by_user` function.
- Rendered task data using `UserTasksStatsOut` Pydantic model with fields:
- `task_id`
- `task_area`
- `created_at`
- `state`

feat: add endpoint to list all tasks for drone user with role validation

---

src/backend/docker-entrypoint.sh

1. Fixes frontend ci not updating index.html
2. Removes migration cmd from entrypoint as we already have different service for it

fix: index.html download always on restart & rm migration from entrypoint script

---

.github/labeler.yml
.github/workflows/pr_label.yml
src/backend/Dockerfile
src/backend/docker-entrypoint.sh
src/backend/pdm.lock
src/backend/pyproject.toml

Small PR to:
- Upgrade image to Python 3.11 + dependencies lock.
- The backend was failing to build due to `root` ownership of `src/backend/templates` dir. I set the permissions to 777 in the entrypoint script.
- Also adds PR labeller workflow / config for automatic labeling.

Upgrade backend to Python 3.11 + fix template dir permissions

---

src/backend/app/waypoints/waypoint_routes.py
src/backend/pdm.lock
src/backend/pyproject.toml

- GSD is accepted from users and altitude is auto calculated, both the options are provided to users
- `drone_flightplan` package version is upgraded to 0.2.1
- Terrain Following is implemented
- For terrain following, DEM file has to be uploaded by users.

Implementing Terrain Following in the waypoint generation API plus GSD 

---

src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
src/frontend/src/components/CreateProject/FormContents/BasicInformation/index.tsx
src/frontend/src/components/CreateProject/FormContents/Contributions/index.tsx

This PR fixes the issues that occurred during the project creation.
- fixes - #119 
- fixes - #118

fix: issue on create project form

---

docker-compose.vm.yml

add external flag on db-data volume on VM

---

.github/labeler.yml

There is a typo in labeling migration label.

fix typo in pr labeller

---

src/backend/app/tasks/task_crud.py
src/backend/app/tasks/task_routes.py

Updated the `task_details` query to map `state` values to more descriptive labels. Added a default case for unexpected values.
- Modified `CASE` statement for `state` labels:
- 'REQUEST_FOR_MAPPING' → 'request logs'
- 'LOCKED_FOR_MAPPING' → 'ongoing'
- 'UNLOCKED_DONE' → 'completed'
- 'UNFLYABLE_TASK' → 'unflyable task'
- Added 'unknown' for any other values

hotfix: query to update state labels in task_details

---

src/backend/app/drones/drone_crud.py
src/backend/app/drones/drone_deps.py
src/backend/app/drones/drone_routes.py
src/backend/app/drones/drone_schemas.py

Continuing this PR: [drone-tm/pull/128](https://github.com/hotosm/drone-tm/pull/128)
Updated Drone Modules using psycopg by replacing encode/databases

Refactor Drone Module using psycopg and Pydantic 

---

src/backend/app/projects/project_schemas.py

- set requires_approval_from_manager_for_locking as optional in Pydantic model

Fix: set requires_approval_from_manager_for_locking as optional

---

src/backend/app/tasks/task_crud.py
src/backend/app/tasks/task_routes.py

- Replaced `update_or_create_task_state` with `request_mapping` for streamlined task state handling.
- Cleaned up the `get_pending_tasks` API by removing redundant logic.
- Fixed task approval issues: now updates existing tasks instead of creating new ones.
- Removed obsolete pending task logic and outdated functions from `request_mapping`.

Fix: task State Management and API Cleanup

---

src/frontend/src/components/Dashboard/RequestLogs/index.tsx
src/frontend/src/modules/user-auth-module/src/components/Authentication/Login/index.tsx
src/frontend/src/routes/types.ts

fix: minor issues

---

src/backend/app/tasks/task_crud.py
src/backend/app/tasks/task_routes.py

This PR updates the SQL query used for fetching request logs, modifying it to filter pending logs based on the current user. Previously, the query returned pending logs for all users, which led to potential data exposure and confusion. Now, only the logs relevant to the logged-in user are displayed.
Key Changes:
The SQL query now includes a condition to filter results based on the user_id, ensuring that each user only sees their own pending requests.
Fixed an issue where users were able to see pending request logs of other users.

Fix: listing request logs based on user

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_schemas.py
src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/views/IndividualProject/index.tsx

(Note: button is visible only if the task is locked by same user).
Screenshot of popup having Go To Task button with user who locked the task :

Feat: Update task locking flow with more detail on tasks

---

src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/components/common/MapLibreComponents/Layers/VectorLayer.ts
src/frontend/src/views/Projects/index.tsx

Insted of using `uuid` for image/icon id, sourceId (id received as a props  eg: task id) with the suffix `-image/icon` has been used.  
[x] Hide map on the project dashboard cards (rendering map on all the cards caused a memory/perfomence issue).

Fix: map crash issue on rerender

---

src/backend/app/projects/project_schemas.py

hot-fix: Issues sloved on image url

Fix(hot-fix): project image_url on project lists

---

src/backend/app/projects/project_schemas.py
src/backend/app/s3.py

This PR improves the `get_image_dir_url` function by adding a check to verify the existence of the image directory in the S3 bucket. Previously, the function generated a URL without confirming whether the directory actually existed. With this change, the function now:
1. Uses `minio_client.list_objects` to check if any objects exist in the specified `image_dir`.
2. Returns the constructed URL if the directory exists.
3. Returns `None` if the directory does not exist.

Fix: check s3 image url existence

---

src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
src/frontend/src/components/CreateProject/DescriptionContents/Contributions/index.tsx
src/frontend/src/components/CreateProject/DescriptionContents/DefineAOI/index.tsx
src/frontend/src/components/CreateProject/DescriptionContents/GenerateTask/index.tsx
src/frontend/src/components/CreateProject/DescriptionContents/KeyParameters/index.tsx
src/frontend/src/components/CreateProject/FormContents/DefineAOI/MapSection/index.tsx
src/frontend/src/components/CreateProject/FormContents/GenerateTask/MapSection/index.tsx
src/frontend/src/components/CreateProject/FormContents/GenerateTask/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/ImageBox/index.tsx
src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/components/Projects/MapSection/index.tsx
src/frontend/src/components/Projects/ProjectCard/index.tsx
src/frontend/src/components/Projects/ProjectCardSkeleton/index.tsx
src/frontend/src/components/common/BaseLayerSwitcher/index.tsx
src/frontend/src/components/common/MapLibreComponents/BaseLayerSwitcher/baseLayers.tsx
src/frontend/src/components/common/MapLibreComponents/BaseLayerSwitcher/index.tsx
src/frontend/src/components/common/MapLibreComponents/LocateUser/index.tsx
src/frontend/src/components/common/MapLibreComponents/map.css
src/frontend/src/components/common/MapLibreComponents/types/index.ts
src/frontend/src/constants/createProject.tsx
src/frontend/src/store/actions/createproject.ts
src/frontend/src/store/slices/createproject.ts
src/frontend/src/views/Projects/index.tsx

- After the task splitting geojson rendered on map trigger the function that takes map canvas using `map.getCanvas` and create blob representing the canvas ,  convert that blob into file and save to state and post as a paload with other project details.
screenshot of Projects page after adding project image on project cards:

Feat: Add project image, base-layer switcher and locate user

---

src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py

This PR updates the MinIO S3 bucket path structure to better organize project files and task-related images:
- **Project-level files** such as `dem.tif` and `map_screenshot.jpg` are stored directly under the project directory.
- **Task-specific images** are now grouped under a dedicated `images` folder within each task directory.
The new structure is as follows:
```
projects/
└── project_id/
├── dem.tif
├── map_screenshot.jpg
└── task_id/
└── images/
├── image_1.jpg
├── image_2.jpg
├── image_3.jpg
```

Refactor: update S3 bucket structure for project files and task images

---

src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py

This pull request introduces a new feature to optionally filter projects based on the current user. 
- Added `filter_by_owner` to the `read_projects` endpoint to filter projects where the `author_id` matches the current user's ID. If `filter_by_owner` is set to `True`, the query will only return projects authored by the current user. If `filter_by_owner` is set to `False` or not provided, all projects will be returned.

Feat: Add optional filter for projects by current user

---

src/backend/app/models/enums.py
src/backend/app/tasks/task_logic.py
src/backend/app/tasks/task_routes.py

This PR introduces a new feature allowing drone operators to unlock a task state by unlocking it if it is locked. This enhancement addresses the need for flexibility in task management, particularly in cases where tasks are mistakenly locked by drone operators.
- **New `unlock` Feature**: Implements functionality to unlock a task if it's locked, enabling correction of mistakes by drone operators.
- **State Validation and Error Handling**: Adds checks to ensure that the task is in the correct state for resetting and verifies that the request is made by the user who locked the task. Provides appropriate error messages for invalid operations.

Feat: add task reset feature for drone operators

---

src/backend/app/projects/project_schemas.py

- Add counts for total and ongoing tasks to project retrieval.
- Updated `all` method to include `total_task_count` and `ongoing_task_count`.

Feat: add counts for total tasks and ongoing tasks in project retrieval

---

src/backend/app/projects/project_logic.py
src/backend/app/tasks/task_splitter.py

- **Description**: 
- Previously, polygons were merged based on the smallest adjacent polygon area.
- Now, small polygons are merged with adjacent polygons that share the maximum boundary length.
- **Before**
- **After**

Fix: Improve polygon merging logic to merge with the polygon having maximum shared boundary

---

src/backend/app/config.py
src/backend/app/projects/image_processing.py
src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/app/s3.py
src/backend/app/waypoints/waypoint_routes.py
src/backend/pdm.lock
src/backend/pyproject.toml

This pull request introduces a comprehensive image processing pipeline that:
DroneImageProcessor Class: Manages the entire processing workflow, including downloading images, processing with NodeODM, and uploading results.
S3 Integration: Uses existing functions in `s3.py` to download the images and upload the processed imagery back to MinIO
FastAPI Background Tasks: Implements background processing to keep the API responsive.
Task Status Tracking: Introduces a TaskManager to track the status of processing tasks.
API Endpoints:
POST `process_imagery/{project_id}/{task_id}/` Initiates processing

Drone Image Processing using Open Drone Map (ODM)

---

src/frontend/src/api/tasks.ts
src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/QuestionBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsInformation/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
src/frontend/src/services/tasks.ts

This Pull request adds information about the uploaded images in the tasks page. 
Image count  and weather the orthophoto is available or not is displayed.
Allow the user to download orthophooto and all the assets after processing is completed.

Display uploaded image information  in frontend 

---

src/backend/app/tasks/task_schemas.py

- Updated the SQL query in `get_tasks_by_user` to include the `project_name` from the `projects` table.
- This ensures that the project name is returned along with task-related data for user tasks.
N/A

feat: added project name to the user tasks query

---

src/frontend/src/App.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/LoadingBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsInformation/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
src/frontend/src/views/UserProfile/index.tsx

Add a button for orthophoto download of the individual task,  download is enabled if the orthophoto available is true.

Feat: download orthophoto

---

src/frontend/src/api/projects.ts
src/frontend/src/components/CreateProject/CreateprojectLayout/index.tsx
src/frontend/src/components/Dashboard/RequestLogs/index.tsx
src/frontend/src/components/Dashboard/TaskLogs/TaskLogsTable.tsx
src/frontend/src/components/Projects/MapSection/VectorLayerWithCluster.tsx
src/frontend/src/components/Projects/MapSection/index.tsx
src/frontend/src/components/Projects/ProjectsHeader/index.tsx
src/frontend/src/services/createproject.ts
src/frontend/src/store/slices/createproject.ts
src/frontend/src/views/Dashboard/index.tsx
src/frontend/src/views/IndividualProject/index.tsx
src/frontend/src/views/Projects/index.tsx

Feat: Filter owner projects, show project name on task logs and other minor updates

---

src/backend/app/migrations/versions/5235ef4afa9c_.py
src/backend/app/models/enums.py

This PR adds two new enums to the project:
- `IMAGE_UPLOADED`: Represents the state when an image has been uploaded.
- `IMAGE_PROCESSED`: Represents the state when an uploaded image has been processed.

Feat: added two new enums such as IMAGE_UPLOADED & IMAGE_PROCESSED

---

src/backend/app/tasks/task_routes.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

N/A 
- Updated the Profit Edit API to use a PATCH request .
- Added logic to verify the old password against the user's current password when updating their profile.
- Fixed an issue where the `updated_at` field was not being correctly fetched in the task read query.

Fix: add Password Verification and Fix updated_at Field Fetch in task details endpoint

---

src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/frontend/src/api/projects.ts
src/frontend/src/components/Projects/MapSection/index.tsx
src/frontend/src/components/Projects/Pagination/index.tsx
src/frontend/src/components/Projects/ProjectsHeader/index.tsx
src/frontend/src/components/common/FormUI/SearchInput/index.tsx
src/frontend/src/constants/index.ts
src/frontend/src/hooks/usePagination.tsx
src/frontend/src/services/createproject.ts
src/frontend/src/store/slices/common.ts
src/frontend/src/views/Projects/index.tsx

This PR updates the pagination response format for better clarity and consistency. The new response structure includes an empty results array and a pagination object with the following fields:
- If projects not found
```json
{
"results": [],
"pagination": {
"has_next": false,
"has_prev": false,
"next_num": null,
"prev_num": null,
"page": 1,
"per_page": 10,
"total": 0
}
}
```
- If project:
```json
{
"results": [
{
"id": "33ca93f6-6ac4-4c91-9dc2-4d52cf14b021",
"slug": "this-is-test-projects-041020240848",
"name": "This is test projects",
"description": "This is test projects",
"per_task_instructions": "",
"requires_approval_from_manager_for_locking": false,
"outline": {
"type": "Polygon",
"coordinates": [
[
[
-69.841946,
18.518616
],
[
-69.841946,
18.510113
],
[
-69.830249,
18.510113
],
[ …
```

Feat: updated pagination on list projects

---

src/backend/app/projects/image_processing.py
src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/app/tasks/task_routes.py
src/backend/app/tasks/task_schemas.py

Feat: Updated the task as completed after process from S3

---

src/backend/app/db/database.py
src/backend/app/main.py
src/backend/app/projects/project_deps.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/pdm.lock
src/backend/pyproject.toml
src/frontend/src/api/projects.ts
src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx
src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
src/frontend/src/constants/index.ts
src/frontend/src/services/project.ts
src/frontend/src/services/tasks.ts
src/frontend/src/views/IndividualProject/index.tsx
src/frontend/src/views/Projects/index.tsx

This PR updates `drone_flightplan` to version 0.3.1 and improves the existing endpoints:
- Now able to retrieve all tasks and their task assets status for a given project.
- Allows for the retrieval of individual task status by `task_id`, or all tasks if no `task_id` is provided.
- **Fixes deprecation warning**: Resolved the deprecated async pool initialization for psycopg. Updated `get_db_connection_pool` to explicitly call `await pool.open()` and refactored `lifespan` to use `async with` for managing the connection pool lifecycle.
The following warning was addressed:
``` 
/project/.venv/lib/python3.11/site-packages/psycopg_pool/pool_async.py:138: RuntimeWarning: opening the async pool AsyncConnectionPool in the constructor is deprecated and will not be supported anymore in a future …
```

Feat: Updated endpoints(download-assets) to fetch task assets status.

---

src/frontend/src/components/GoogleAuth/index.tsx
src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/components/common/UserProfile/index.tsx
src/frontend/src/modules/user-auth-module/src/components/Authentication/Login/index.tsx

This PR includes the feature to enable user details updation/addition if the user is logged in as a different role.
For example, if the user is already signed in as a Project creator and wants to sign in as a drone pilot, he/she can log in with the same email/user_id but needs to update details related to the drone pilot. So, if he/she logs in as a drone operator for the first time, the system redirects to the complete profile section.

Fix: Complete profile as a new role

---

src/backend/app/migrations/versions/4ea77c60b715_.py
src/backend/app/models/enums.py
src/backend/app/projects/image_processing.py
src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/app/tasks/task_logic.py
src/backend/app/tasks/task_routes.py
src/backend/app/tasks/task_schemas.py
src/frontend/src/components/Dashboard/RequestLogs/index.tsx
src/frontend/src/components/Dashboard/TaskLogs/TaskLogsTable.tsx
src/frontend/src/components/Dashboard/TaskLogs/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/PopoverBox/ImageBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsBox/index.tsx
src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
src/frontend/src/components/DroneOperatorTask/Header/index.tsx
src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
src/frontend/src/components/IndividualProject/MapSection/Legend.tsx
src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/constants/index.ts
src/frontend/src/services/droneOperator.ts
src/frontend/src/store/actions/droneOperatorTask.ts
src/frontend/src/store/slices/droneOperartorTask.ts
src/frontend/src/utils/index.ts
src/frontend/src/views/IndividualProject/index.tsx
src/frontend/src/views/TaskDescription/index.tsx

feat: add image processing failure handling and retry mechanism for drone task image uploads & re-run process

---

src/backend/app/projects/image_processing.py
src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py
src/backend/app/s3.py
src/backend/pdm.lock
src/backend/pyproject.toml
src/frontend/src/components/DroneOperatorTask/DescriptionSection/DescriptionBox/index.tsx
src/frontend/src/components/DroneOperatorTask/ModalContent/TaskOrthophotoPreview.tsx
src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
src/frontend/src/constants/modalContents.tsx
src/frontend/src/store/actions/droneOperatorTask.ts
src/frontend/src/store/slices/droneOperartorTask.ts

This PR introduces the functionality to process orthophoto images generated by the ODM (OpenDroneMap) pipeline, save them in Cloud-Optimized GeoTIFF (COG) format, and provide an API endpoint to serve tiles of the orthophoto. Key features include:
- Updated image processing logic to extract orthophoto TIFF from ODM assets and upload it to S3.
- Added an API endpoint to serve PNG image tiles of the orthophoto based on `z`, `x`, and `y` indices (zoom and tile coordinates).
- used `rio-tiler` to efficiently generate tiles from the COG file.
- Error handling for tiles outside the image bounds.

feat: added orthophoto tile endpoints for COG image serving

---

src/backend/app/projects/image_processing.py

When processing imagery with PyODM (ODM), the resulting orthophoto TIFF file is output with EPSG:32645 by default. However, for web visualization using Maplibre-cog-protocol, EPSG:3857 projection is required. 
This update adds functionality to automatically reproject the orthophoto from the default EPSG:32645 to EPSG:3857 before uploading to S3. This allows for seamless integration with web-based map visualizations, which rely on EPSG:3857 for proper rendering.
This functionality is aligned with the ongoing discussions about passing different output projections to ODM. For more context, please refer to the following community link:
[Passing different output projections to ODM (e.g., --proj flag)](https://community.opendronemap.org/t/passing-different-output-projections-to-odm-eg-a-proj-fla …

feat: Add reprojection of orthophoto to EPSG:3857 before uploading to S3

---

src/backend/app/projects/image_processing.py
src/frontend/src/components/DroneOperatorTask/DescriptionSection/UploadsBox/index.tsx
src/frontend/src/constants/modalContents.tsx

This pull request introduces a new feature to upload an align.laz file. The file should be with the name `align.laz` and should be within the same folder as the images.
This will be critical to the workflow to ensure alignment of multiple missions, similar to multi-temporal example here:
https://docs.opendronemap.org/map-accuracy/#multi-temporal-datasets

Upload align.laz along with Drone Images

---

src/frontend/src/components/DroneOperatorTask/MapSection/index.tsx

…not valid
Example: Fixes #123
- Reset state of takeoff location point if the location point is invalid. So that user can select takeoff point again

refactor(frontend): reset takeoff point location, incase of errors

---

src/frontend/src/components/IndividualProject/MapSection/index.tsx

fix: disable popup trigger if user signin as `ReGULATOR`

---

src/backend/app/tasks/task_splitter.py

- Resolved issue where very small areas were not merging with their nearest neighbor during task splitting.  
- Before:
- After:

fix: ensure small areas merge with the nearest one in task splitting

---

src/backend/app/tasks/task_logic.py
src/backend/app/tasks/task_schemas.py

Example: Fixes #123
This PR addresses two issues:
- The project creator was unable to lock tasks.
- A validation error occurred in the TaskDetailsOut schema, where the gsd_cm_px field expected a float but received a None value.

fix: task locking and validation error in project creator

---

src/backend/app/projects/project_routes.py
src/backend/app/utils.py
src/backend/app/waypoints/waypoint_routes.py

- Added flight plan time .  
- Updated waypoint count to reflect changes in terrain-follow mode.  

fix: update the flight plan time &  waypoints counts if user terrian

---

src/backend/app/gcp/gcp_crud.py
src/backend/app/gcp/gcp_routes.py

This Pull Request has a change in approach to calculate the drone image bounding box. 
In this approach, I have first calculated the image footprint height and width, and then used them to calculate the bounding box by adding half a width to each side of the centroid of the image and same to the height.

fix: calculate bbox for the drone image

---

src/backend/app/tasks/task_routes.py
src/backend/app/tasks/task_schemas.py
src/backend/app/waypoints/waypoint_routes.py
src/backend/app/waypoints/waypoint_schemas.py

- generate and download KMZ files with placemarks.
- added centroid in task details endpoint

feat: generate and download KMZ files with placemarks

---

src/backend/app/gcp/gcp_crud.py
src/backend/app/gcp/gcp_routes.py

I have tried to solve the error in calculation of drone image footprints in this pull request.

Gcp calculation

---

docker-compose.yml
src/backend/app/config.py
src/backend/app/projects/image_processing.py
src/backend/app/projects/project_logic.py
src/backend/app/projects/project_routes.py

This PR introduces new endpoints to handle the processing of all task images associated with Areas of Interest (AOI).  

feat: update drone image processor to handle single and multiple tasks

---

src/backend/app/users/user_schemas.py

When a user is created for the first time, the hashed password is saved in the database.  
- Ensure the password is hashed and saved during user creation if provided."

Ensure password is saved during user creation if provided

---

src/frontend/src/views/LandingPage/index.tsx

Ignore ts for AnimatePresence, cause it caused `AnimatePresence cannot be used as a JSX component` issue on build.

hot-fix: ignore ts for animate presence of framer-motion

---

src/backend/app/projects/project_routes.py
src/backend/app/waypoints/waypoint_routes.py
src/backend/pyproject.toml
src/backend/uv.lock

Implement Flightplan Rotation

---

src/backend/app/s3.py
src/frontend/src/components/IndividualProject/Contributions/TableSection/index.tsx
src/frontend/src/components/IndividualProject/GcpEditor/index.tsx
src/frontend/src/components/IndividualProject/MapSection/index.tsx
src/frontend/src/components/IndividualProject/ModalContent/ChooseProcessingParameter.tsx
src/frontend/src/components/RegulatorsApprovalPage/Description/DescriptionSection.tsx
src/frontend/src/components/common/Breadcrumb/index.tsx
src/frontend/src/components/common/MapLibreComponents/COGOrthophotoViewer/index.tsx
src/frontend/src/constants/modalContents.tsx
src/frontend/src/constants/projectDescription.ts
src/frontend/src/services/project.ts
src/frontend/src/store/slices/project.ts

Feat/Visualize task's and overall project orthophoto, options to start  processing without GCP  and other relative changes 

---

src/backend/app/tasks/task_logic.py

Previously, the project creator was unable to change the state of a task if another user had locked it due to a permission issue. This has now been fixed by adding a check to allow the project creator to unlock the task unless it is locked by another user.  
- Added a condition to verify if the user is the project creator.  
- If the user is neither the project creator nor the one who locked the task, a `403 Forbidden` error is raised.  
```python
is_author = project["author_id"] == user_id
if not is_author and user_id != locked_user_id:
raise HTTPException(
status_code=403,
detail="You cannot unlock this task as it is locked by another user.",
)

Fix Permission Issue for Task State Change by Project Creator

---

src/backend/app/models/enums.py
src/backend/app/waypoints/waypoint_routes.py
src/backend/packages/drone-flightplan/drone_flightplan/calculate_parameters.py
src/backend/packages/drone-flightplan/drone_flightplan/create_flightplan.py
src/backend/packages/drone-flightplan/drone_flightplan/drone_type.py
src/backend/packages/drone-flightplan/drone_flightplan/waypoints.py

Update support for DJI air 3 drones

---

src/backend/app/waypoints/waypoint_routes.py
src/backend/packages/drone-flightplan/README.md
src/backend/packages/drone-flightplan/drone_flightplan/calculate_parameters.py
src/backend/packages/drone-flightplan/drone_flightplan/drone_type.py
src/frontend/src/api/tasks.ts
src/frontend/src/components/DroneOperatorTask/DescriptionSection/index.tsx
src/frontend/src/components/DroneOperatorTask/MapSection/MapSection.tsx
src/frontend/src/constants/taskDescription.ts
src/frontend/src/services/tasks.ts
src/frontend/src/store/actions/droneOperatorTask.ts
src/frontend/src/store/slices/droneOperartorTask.ts

Final part of https://github.com/hotosm/drone-tm/issues/543 and https://github.com/hotosm/drone-tm/issues/537
- Small bit of frontend code to add a toggle for drone type.
- This could be improved - it should probably be a dropdown in future as the list grows.
- Note I still need to test and improve the Potensic flightplan generation properly.
- Image interval to 2.
- Use both flights if present.
> [!NOTE]
> The hard limit of 50 waypoints is overcome by adding multiple flights to the same sqlite database for the Potensic Pro app.
- 📗 Update any related documentation and include any …

Add toggle to select drone type for flightplan generation & fix drone param calcs
